# Generated by Django 3.1.7 on 2021-04-02 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('price', models.DecimalField(decimal_places=2, max_digits=6)),
                ('about_item', models.TextField(null=True)),
                ('category', models.CharField(choices=[('drinks', 'Drinks'), ('appetizer', 'Appetizer'), ('main course', 'Main Course'), ('dessert', 'Dessert')], max_length=20)),
                ('available', models.BooleanField(default=False)),
            ],
        ),
    ]
